### Breast Cancer Classifier

Classifies if the tumor is benign, which class takes value of 2 or malignant, which class takes value of 4.

#### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#### Importing the dataset

In [3]:
dataset = pd.read_csv(r'C:\Users\turan\Desktop\Kaggle\breast_cancer.csv')

In [4]:
dataset.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1                3                1        1      2  
1           10                3                2        1      2  
2            2                3                1        1      2  
3            4                3                7        1      2  
4            1                3                1        1      2

In [5]:
dataset.shape

(683, 11)

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sample code number           683 non-null    int64
 1   Clump Thickness              683 non-null    int64
 2   Uniformity of Cell Size      683 non-null    int64
 3   Uniformity of Cell Shape     683 non-null    int64
 4   Marginal Adhesion            683 non-null    int64
 5   Single Epithelial Cell Size  683 non-null    int64
 6   Bare Nuclei                  683 non-null    int64
 7   Bland Chromatin              683 non-null    int64
 8   Normal Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB


In [7]:
dataset.describe()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
count        6.830000e+02       683.000000               683.000000   
mean         1.076720e+06         4.442167                 3.150805   
std          6.206440e+05         2.820761                 3.065145   
min          6.337500e+04         1.000000                 1.000000   
25%          8.776170e+05         2.000000                 1.000000   
50%          1.171795e+06         4.000000                 1.000000   
75%          1.238705e+06         6.000000                 5.000000   
max          1.345435e+07        10.000000                10.000000   

       Uniformity of Cell Shape  Marginal Adhesion  \
count                683.000000         683.000000   
mean                   3.215227           2.830161   
std                    2.988581           2.864562   
min                    1.000000           1.000000   
25%                    1.000000           1.000000   
50%                    1.000000           1.000000   
75%                    5.000000           4.000000   
max                   10.000000          10.000000   

       Single Epithelial Cell Size  Bare Nuclei  Bland Chromatin  \
count                   683.000000   683.000000       683.000000   
mean                      3.234261     3.544656         3.445095   
std                       2.223085     3.643857         2.449697   
min                       1.000000     1.000000         1.000000   
25%                       2.000000     1.000000         2.000000   
50%                       2.000000     1.000000         3.000000   
75%                       4.000000     6.000000         5.000000   
max                      10.000000    10.000000        10.000000   

       Normal Nucleoli     Mitoses       Class  
count       683.000000  683.000000  683.000000  
mean          2.869693    1.603221    2.699854  
std           3.052666    1.732674    0.954592  
min           1.000000    1.000000    2.000000  
25%           1.000000    1.000000    2.000000  
50%           1.000000    1.000000    2.000000  
75%           4.000000    1.000000    4.000000  
max          10.000000   10.000000    4.000000

In [8]:
dataset.nunique()

Sample code number             630
Clump Thickness                 10
Uniformity of Cell Size         10
Uniformity of Cell Shape        10
Marginal Adhesion               10
Single Epithelial Cell Size     10
Bare Nuclei                     10
Bland Chromatin                 10
Normal Nucleoli                 10
Mitoses                          9
Class                            2
dtype: int64

In [9]:
dataset.loc[dataset['Class']==2, 'Class'] = 0
dataset.loc[dataset['Class']==4, 'Class'] = 1

For beign we convert the name from 2 t0 0, for malignant we convert the from 4 to 1.

In [10]:
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

#### Splitting the dataset into the training set and test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

#### Feature scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#### Logistic Regression model

In [13]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()
lg.fit(X_train, y_train)

LogisticRegression()

In [14]:
lg_pred = lg.predict(X_test)

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
print('Accuracy: ',accuracy_score(y_test,lg_pred))
print(f'\nConfusion matrix:\n{confusion_matrix(y_test, lg_pred)}')

Accuracy:  0.9562043795620438

Confusion matrix:
[[84  3]
 [ 3 47]]


#### K-nearest-neighbours model

In [16]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier()
kn.fit(X_train, y_train)

KNeighborsClassifier()

In [17]:
kn_pred = kn.predict(X_test)

In [18]:
print('Accuracy: ',accuracy_score(y_test,kn_pred))
print(f'\nConfusion matrix:\n{confusion_matrix(y_test, kn_pred)}')

Accuracy:  0.9562043795620438

Confusion matrix:
[[83  4]
 [ 2 48]]


#### Naive Bayes model

In [19]:
from sklearn.naive_bayes import GaussianNB
gs = GaussianNB()
gs.fit(X_train,  y_train)

GaussianNB()

In [20]:
gs_pred = gs.predict(X_test)

In [21]:
print('Accuracy: ',accuracy_score(y_test,gs_pred))
print(f'\nConfusion matrix:\n{confusion_matrix(y_test, gs_pred)}')

Accuracy:  0.948905109489051

Confusion matrix:
[[80  7]
 [ 0 50]]


#### Support Vector Machine model

In [22]:
from sklearn.svm import SVC
sm = SVC()
sm.fit(X_train, y_train)

SVC()

In [23]:
sm_pred = sm.predict(X_test)

In [24]:
print('Accuracy: ',accuracy_score(y_test,sm_pred))
print(f'\nConfusion matrix:\n{confusion_matrix(y_test, sm_pred)}')

Accuracy:  0.9562043795620438

Confusion matrix:
[[82  5]
 [ 1 49]]


#### Decision Tree model

In [25]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion='entropy')
dt.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [26]:
dt_pred = dt.predict(X_test)

In [27]:
print('Accuracy: ',accuracy_score(y_test, dt_pred))
print(f'\nConfusion matrix:\n{confusion_matrix(y_test, dt_pred)}')

Accuracy:  0.9562043795620438

Confusion matrix:
[[84  3]
 [ 3 47]]


#### Random Forest model

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, criterion='gini')
rf.fit(X_train, y_train)

In [ ]:
rf_pred = rf.predict(X_test)

In [ ]:
print('Accuracy: ',accuracy_score(y_test, rf_pred))
print(f'\nConfusion matrix:\n{confusion_matrix(y_test, rf_pred)}')